---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi8/ubi:latest  # vanilla image!

options:
  user: '1000'  # (optional) sets the username or UID
  # tags:  # (optional) sets tags
  #   - 'ee_development:latest'

dependencies:
  python_interpreter:
    package_system: python311  # (optional) name of a Python interpreter OS package to install
    python_path: /usr/bin/python3.11  # (optional) path to the Python interpreter to use

  ansible_core:  # (optional) install ansible-core if the base image doesn't already contain it
    package_pip: https://github.com/ansible/ansible/archive/refs/tags/v2.13.2.tar.gz   # install from a GH ref tarball

  ansible_runner:  # (optional) install ansible-runner if the base image doesn't already contain it
    package_pip: ansible-runner==2.3.3   # install specific version from PyPI

  # lists of Ansible collections and/or roles to install (or the filename of an Ansible Galaxy CLI requirements YAML file)

  # the contents of this key are not validated by ansible-builder itself; they will be written to `requirements.yml` in
  # the root of the generated build context and consumed directly by the ansible-galaxy CLI during the build
  galaxy:
    collections:
    - cisco.ios  # base windows support
    - cisco.nxos  # base windows support
    - ansible.utils
    - ansible.netcommon

  # explicit list of Python dependencies to install (in addition to those declared by the collections above)
  python:
  - address
  # explicit list of bindep entries for OS packages to install (in addition to those declared by the collections above)
  system:
  - iputils [platform:rpm]
