---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/aap/ansible-automation-platform-20-ee-29-rhel8'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-20-early-access/ansible-builder-rhel8'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt


additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append:
    - RUN ls -la /etc
