---
version: 3

images:
  base_image:
    name: quay.io/acme_corp/network-ee:latest

dependencies:
  galaxy:
    collections:
    - arista.cvp
    - arista.avd
  
  python:
  - address
  
options:
  package_manager_path: /usr/bin/microdnf
