---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.18.5

dependencies:
  galaxy:
    collections:
    - ansible.windows
    - community.windows
    - ansible.posix
    - community.general
    - redhat.rhel_system_roles
    - redhat.rhel_idm

  python:
  - address


options:
  package_manager_path: /usr/bin/microdnf
